"""
verify_cuml.py
==============
Verifica che cuML UMAP + HDBSCAN funzionino su tutti i nodi GPU.
Se trova worker-02 con nvjitlink vecchio, lo aggiorna e ritesta.
"""
import ray

RAY_ADDRESS = "ray://datalab-rayclnt.unitus.it:10001"


@ray.remote(num_gpus=1)
def check_and_fix() -> dict:
    import subprocess, sys, socket, os

    node = socket.gethostname()

    # ── Versione nvjitlink ───────────────────────────────────────────────
    r = subprocess.run(
        [sys.executable, "-m", "pip", "show", "nvidia-nvjitlink-cu12"],
        capture_output=True, text=True,
    )
    nvjit_ver = next(
        (l.split(":", 1)[1].strip() for l in r.stdout.splitlines()
         if l.startswith("Version")), "n/a"
    )

    # Controlla se serve aggiornamento (deve essere >= 12.9)
    try:
        major, minor = map(int, nvjit_ver.split(".")[:2])
        needs_update = (major < 12) or (major == 12 and minor < 9)
    except Exception:
        needs_update = True

    if needs_update:
        print(f"[{node}] nvjitlink {nvjit_ver} < 12.9 — aggiorno...", flush=True)
        r2 = subprocess.run(
            [sys.executable, "-m", "pip", "install",
             "nvidia-nvjitlink-cu12>=12.9",
             "--extra-index-url", "https://pypi.nvidia.com",
             "--upgrade", "--break-system-packages",
             "--quiet", "--no-warn-script-location"],
            capture_output=True, text=True, timeout=300,
        )
        if r2.returncode != 0:
            return {"node": node, "ok": False,
                    "error": f"pip failed: {r2.stderr[-200:]}"}
        # Versione aggiornata
        r3 = subprocess.run(
            [sys.executable, "-m", "pip", "show", "nvidia-nvjitlink-cu12"],
            capture_output=True, text=True,
        )
        nvjit_ver = next(
            (l.split(":", 1)[1].strip() for l in r3.stdout.splitlines()
             if l.startswith("Version")), "?")
        print(f"[{node}] nvjitlink aggiornato → {nvjit_ver}", flush=True)
    else:
        print(f"[{node}] nvjitlink {nvjit_ver} OK", flush=True)

    # ── Test cuML UMAP + HDBSCAN ─────────────────────────────────────────
    # Nota: usa triple-quote normale (non f-string) per evitare eval prematuro
    BASE = "/usr/local/lib/python3.12/dist-packages"
    test_script = (
        "import ctypes, os, glob\n"
        "BASE = '" + BASE + "'\n"
        "lib_dirs = (glob.glob(BASE+'/nvidia/*/lib') + glob.glob(BASE+'/nvidia/*/lib64')\n"
        "           + glob.glob(BASE+'/*/lib64') + glob.glob(BASE+'/*.libs'))\n"
        "os.environ['LD_LIBRARY_PATH'] = ':'.join(lib_dirs)\n"
        "for lib in [BASE+'/rapids_logger/lib64/librapids_logger.so',\n"
        "            BASE+'/librmm/lib64/librmm.so',\n"
        "            BASE+'/libraft/lib64/libraft.so',\n"
        "            BASE+'/libcuml/lib64/libcuml++.so']:\n"
        "    if os.path.exists(lib):\n"
        "        try: ctypes.CDLL(lib, mode=ctypes.RTLD_GLOBAL)\n"
        "        except: pass\n"
        "import cuml\n"
        "from cuml.manifold import UMAP\n"
        "from cuml.cluster import HDBSCAN\n"
        "import numpy as np, cupy as cp\n"
        "X = cp.asarray(np.random.randn(500, 20).astype('float32'))\n"
        "Z = UMAP(n_components=2, n_neighbors=10, random_state=42).fit_transform(X)\n"
        "h = HDBSCAN(min_cluster_size=30, gen_min_span_tree=True)\n"
        "h.fit(Z)\n"
        "labels = h.labels_.tolist()\n"
        "n_cl = len(set(labels)) - (1 if -1 in labels else 0)\n"
        "dbcv = float(h.relative_validity_) if hasattr(h, 'relative_validity_') else float('nan')\n"
        "print(f'cuML {cuml.__version__}  UMAP {tuple(Z.shape)}  HDBSCAN k={n_cl}  dbcv={dbcv:.3f}')\n"
    )

    r4 = subprocess.run(
        [sys.executable, "-c", test_script],
        capture_output=True, text=True, timeout=120,
    )

    if r4.returncode == 0:
        out = r4.stdout.strip()
        print(f"[{node}] ✓ {out}", flush=True)

        # Scrivi sitecustomize.py se mancante
        sc_path = f"{BASE}/ray/thirdparty_files/sitecustomize.py"
        sc_snippet = (
            "\n# rapids_preload — auto-generated by verify_cuml.py\n"
            "import ctypes as _ctypes, os as _os, glob as _glob\n"
            "_BASE = '" + BASE + "'\n"
            "_lib_dirs = (_glob.glob(_BASE+'/nvidia/*/lib') + _glob.glob(_BASE+'/nvidia/*/lib64')\n"
            "            + _glob.glob(_BASE+'/*/lib64') + _glob.glob(_BASE+'/*.libs'))\n"
            "_os.environ['LD_LIBRARY_PATH'] = ':'.join(_lib_dirs)\n"
            "for _lib in [_BASE+'/rapids_logger/lib64/librapids_logger.so',\n"
            "             _BASE+'/librmm/lib64/librmm.so',\n"
            "             _BASE+'/libraft/lib64/libraft.so',\n"
            "             _BASE+'/libcuml/lib64/libcuml++.so']:\n"
            "    if _os.path.exists(_lib):\n"
            "        try: _ctypes.CDLL(_lib, mode=_ctypes.RTLD_GLOBAL)\n"
            "        except Exception: pass\n"
        )
        try:
            existing = open(sc_path).read() if os.path.exists(sc_path) else ""
            if "rapids_preload" not in existing:
                with open(sc_path, "a") as f:
                    f.write(sc_snippet)
                print(f"[{node}] sitecustomize.py scritto → {sc_path}", flush=True)
            else:
                print(f"[{node}] sitecustomize.py già presente", flush=True)
        except Exception as e:
            print(f"[{node}] Warning sitecustomize: {e}", flush=True)

        return {"node": node, "ok": True, "nvjit": nvjit_ver, "test": out}
    else:
        err = r4.stderr[-400:].strip()
        print(f"[{node}] ✗ FAILED:\n{err}", flush=True)
        return {"node": node, "ok": False, "nvjit": nvjit_ver, "error": err}


def main():
    ray.init(address=RAY_ADDRESS, ignore_reinit_error=True,
             log_to_driver=True)

    n_gpu = int(ray.cluster_resources().get("GPU", 0))
    print(f"\nGPU nel cluster: {n_gpu} — verifica cuML su tutti i nodi\n")

    futures = [check_and_fix.remote() for _ in range(n_gpu)]
    results = ray.get(futures)

    print("\n" + "═" * 65)
    all_ok = True
    for r in results:
        icon = "✓" if r["ok"] else "✗"
        print(f"  {icon} {r['node']}  nvjitlink={r.get('nvjit','?')}  "
              + (r.get("test", "") if r["ok"] else f"FAILED: {r.get('error','')[:80]}"))
        if not r["ok"]:
            all_ok = False

    print()
    if all_ok:
        print("  ✓ cuML OK su tutti i nodi — lancia: python step03_clustering.py")
    else:
        print("  ⚠ Problemi su qualche nodo — vedi sopra.")
    print()
    ray.shutdown()


if __name__ == "__main__":
    main()
